name: Setup
description: Install Python, UV, and just

runs:
  using: composite
  steps:
  - uses: actions/setup-python@v6
    with:
      python-version: '3.14'

  - uses: astral-sh/setup-uv@v7
    with:
      version: "latest"
      enable-cache: true

  - uses: extractions/setup-just@v3
