"""Gitignore boost implementation."""

import subprocess
import urllib.error
import urllib.request

from loguru import logger

from pimp_my_repo.core.boosts.base import Boost
from pimp_my_repo.core.tools.git import COMMIT_AUTHOR

_GITIGNORE_API = "https://www.toptal.com/developers/gitignore/api"
_GITIGNORE_HEADER = "# ==== Generated by pimp-my-repo (gitignore.io) ===="
_ALWAYS_TEMPLATES = ["macos", "windows", "linux", "jetbrains+all", "visualstudiocode"]


class GitignoreBoost(Boost):
    """Boost for adding a comprehensive .gitignore file."""

    def _run_git(self, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
        cmd = ["git", *args]
        return subprocess.run(  # noqa: S603
            cmd,
            cwd=self.tools.repo_controller.path,
            capture_output=True,
            text=True,
            check=check,
        )

    def _detect_templates(self) -> list[str]:
        """Detect project type and return matching gitignore.io template names."""
        templates = list(_ALWAYS_TEMPLATES)

        if any(
            (self.tools.repo_controller.path / f).exists() for f in ["pyproject.toml", "setup.py", "requirements.txt"]
        ):
            templates.append("python")
        if (self.tools.repo_controller.path / "package.json").exists():
            templates.append("node")
        if (self.tools.repo_controller.path / "Cargo.toml").exists():
            templates.append("rust")
        if (self.tools.repo_controller.path / "go.mod").exists():
            templates.append("go")
        if (self.tools.repo_controller.path / "pom.xml").exists():
            templates.extend(["java", "maven"])
        if any((self.tools.repo_controller.path / f).exists() for f in ["build.gradle", "build.gradle.kts"]):
            templates.extend(["java", "gradle"])

        return templates

    def _fetch_gitignore(self, templates: list[str]) -> str | None:
        """Fetch .gitignore content from the gitignore.io API."""
        url = f"{_GITIGNORE_API}/{','.join(templates)}"
        try:
            request = urllib.request.Request(url)  # noqa: S310
            request.add_header("User-Agent", "pimp-my-repo")
            with urllib.request.urlopen(request, timeout=3) as response:  # noqa: S310
                return response.read().decode("utf-8")  # type: ignore[no-any-return]
        except (urllib.error.URLError, urllib.error.HTTPError, OSError) as exc:
            logger.warning(f"Failed to fetch .gitignore from gitignore.io: {exc}")
            return None

    def _append_gitignore(self, generated: str) -> None:
        """Append generated content to .gitignore, or create it if absent."""
        gitignore_path = self.tools.repo_controller.path / ".gitignore"

        if not gitignore_path.exists():
            gitignore_path.write_text(f"{_GITIGNORE_HEADER}\n{generated}", encoding="utf-8")
            return

        existing = gitignore_path.read_text(encoding="utf-8")
        if _GITIGNORE_HEADER in existing:
            logger.info(".gitignore already contains generated content, skipping append")
            return

        separator = "" if existing.endswith("\n") else "\n"
        content = f"{existing}{separator}\n{_GITIGNORE_HEADER}\n{generated}"
        gitignore_path.write_text(content, encoding="utf-8")

    def _reset_git_tracking(self) -> None:
        """Untrack all files then re-add, so gitignored files leave the index."""
        self._run_git("rm", "-r", "--cached", ".")
        self._run_git("add", "-A")

    def apply(self) -> None:
        """Fetch .gitignore from gitignore.io, commit it, then reset git tracking."""
        templates = self._detect_templates()
        logger.info(f"Detected gitignore templates: {templates}")

        generated = self._fetch_gitignore(templates)
        if generated is None:
            msg = "Could not fetch .gitignore content from gitignore.io"
            raise RuntimeError(msg)

        self._append_gitignore(generated)
        logger.info("Written .gitignore")
        self._commit_gitignore()

        logger.info("Resetting git tracking to honour new .gitignore rules...")
        self._reset_git_tracking()

    def _commit_gitignore(self) -> None:
        """Commit the .gitignore addition if something changed."""
        self._run_git("add", ".gitignore")
        if not self._run_git("status", "--porcelain", check=False).stdout.strip():
            return
        self._run_git("commit", "--author", COMMIT_AUTHOR, "--no-verify", "-m", "✨ Add .gitignore")

    def commit_message(self) -> str:
        """Generate commit message for Gitignore boost."""
        return "🧹 Remove gitignored files from tracking"
