name: Checks

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-all
    - run: just check-ruff

  check-mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-all
    - run: just check-mypy

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-test
    - run: just cover-xml
    - name: Extract coverage percentage
      run: |
        COVERAGE=$(just cover-percentage)
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE%"

  test-e2e:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: https://github.com/django/django.git
            rev: edd899786851f6285abbc3c272f4f5ec0e48a74c
          - repo: https://github.com/bottlepy/bottle.git
            rev: 2a743a302a71460bfe4c0b8b7cb99a306b0328c6
          - repo: https://github.com/psf/requests.git
            rev: bc04dfd6dad4cb02cd92f5daa81eb562d280a761
          - repo: https://github.com/simplejson/simplejson.git
            rev: f7122a4f60659431b39acbf0b7ad96775642ee02
          - repo: https://github.com/docopt/docopt.git
            rev: 8fea867d4220f1095dae9d6264ec5aa4031fb712
          - repo: https://github.com/pwaller/pyfiglet.git
            rev: e7590f2b80a403db9605750df8a51198759757ee
          - repo: https://github.com/pallets/itsdangerous.git
            rev: 672971d66a2ef9f85151e53283113f33d642dabd
          - repo: https://github.com/mkali-weizmann/cavity-design.git
            rev: ea21f1c759e473dd5e9c843230d2429501637026
          - repo: https://github.com/pandas-dev/pandas.git
            rev: 9279635617e71d156a8fddb40d6011850360057b
          - repo: https://github.com/scikit-learn/scikit-learn.git
            rev: cc4843adf8bcbbe8a6d70ae0b4f490e11c010fa5
          - repo: https://github.com/httpie/httpie.git
            rev: 5b604c37c6c67e18e7c3e9aee6c88a8c22b98345
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-test
    - name: Run E2E test - ${{ matrix.repo }}
      run: just test-e2e ${{ matrix.repo }} ${{ matrix.rev }}
    - name: Upload PMR logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pmr-logs-${{ strategy.job-index }}
        path: ~/.local/state/pmr/*.log
        if-no-files-found: ignore
