name: Checks

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-all
    - run: just check-ruff

  check-mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-all
    - run: just check-mypy

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-test
    - run: just cover-xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: asaf-kali/pimp-my-repo
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Extract coverage percentage
      run: |
        COVERAGE=$(just cover-percentage)
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE%"

  test-e2e:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: https://github.com/django/django.git
            rev: edd89978
          - repo: https://github.com/bottlepy/bottle.git
            rev: 2a743a30
          - repo: https://github.com/psf/requests.git
            rev: bc04dfd6
          - repo: https://github.com/simplejson/simplejson.git
            rev: f7122a4f
          - repo: https://github.com/docopt/docopt.git
            rev: 8fea867d
          - repo: https://github.com/pwaller/pyfiglet.git
            rev: e7590f2b
          - repo: https://github.com/pallets/itsdangerous.git
            rev: 672971d6
          - repo: https://github.com/mkali-weizmann/cavity-design.git
            rev: ea21f1c7
          - repo: https://github.com/pandas-dev/pandas.git
            rev: 92796356
          - repo: https://github.com/scikit-learn/scikit-learn.git
            rev: cc4843ad
          - repo: https://github.com/httpie/httpie.git
            rev: 5b604c37
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup
    - run: just install-test
    - name: Run E2E test - ${{ matrix.repo }}
      run: just test-e2e ${{ matrix.repo }} ${{ matrix.rev }}
    - name: Upload PMR logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pmr-logs-${{ strategy.job-index }}
        path: ~/.local/state/pmr/*.log
        if-no-files-found: ignore
